import type { Theme } from './types'

export const themes: Record<string, Theme> = {
  classic: {
    text: '#2f3542',
    muted: '#64748b',
    primary: '#2563eb',
    soft: '#f1f5f9',
    codeBg: '#0f172a',
    codeText: '#e2e8f0'
  },
  clean: {
    text: '#1f2937',
    muted: '#6b7280',
    primary: '#0f766e',
    soft: '#f8fafc',
    codeBg: '#111827',
    codeText: '#f9fafb'
  },
  business: {
    text: '#273142',
    muted: '#667085',
    primary: '#7c3aed',
    soft: '#f5f3ff',
    codeBg: '#1e1b4b',
    codeText: '#ede9fe'
  },
  analytics: {
    text: '#1e293b',
    muted: '#475569',
    primary: '#1e40af',
    soft: '#eff6ff',
    codeBg: '#0b1220',
    codeText: '#dbeafe',
    accent: '#f59e0b',
    background: '#f8fafc',
    border: '#d8e5f7',
    surface: 'rgba(255,255,255,0.86)',
    variant: 'analytics'
  },
  education: {
    text: '#1e1b4b',
    muted: '#4c4a74',
    primary: '#4f46e5',
    soft: '#eef2ff',
    codeBg: '#312e81',
    codeText: '#fff7ed',
    accent: '#f97316',
    background: '#fff7ed',
    border: '#c7d2fe',
    surface: '#ffffff',
    variant: 'education'
  },
  uiux_001: {
    label: 'SaaS 数据看板',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#111827',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Glassmorphism + Flat Design',
    variant: 'light'
  },
  uiux_002: {
    label: 'AI 对话平台',
    text: '#111827',
    muted: '#475569',
    primary: '#6366F1',
    soft: '#F5F5F5',
    codeBg: '#111827',
    codeText: '#f8fafc',
    accent: '#10B981',
    background: '#F5F5F5',
    border: '#10B981',
    surface: '#ffffff',
    style: 'AI-Native UI + Minimalism',
    variant: 'light'
  },
  uiux_003: {
    label: '奢华电商',
    text: '#111827',
    muted: '#4b5563',
    primary: '#000000',
    soft: '#FFFFFF',
    codeBg: '#111827',
    codeText: '#f8fafc',
    accent: '#FFD700',
    background: '#FFFFFF',
    border: '#FFD700',
    surface: '#ffffff',
    style: 'Liquid Glass + Glassmorphism',
    variant: 'light'
  },
  uiux_005: {
    label: '健康疗愈',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0284c7',
    soft: '#F5F5F5',
    codeBg: '#0f172a',
    codeText: '#f0f9ff',
    accent: '#22C55E',
    background: '#F5F5F5',
    border: '#90EE90',
    surface: '#ffffff',
    style: 'Neumorphism + Soft UI Evolution',
    variant: 'light'
  },
  uiux_006: {
    label: '创意机构',
    text: '#111827',
    muted: '#374151',
    primary: '#FF0000',
    soft: '#FFFFFF',
    codeBg: '#111827',
    codeText: '#f8fafc',
    accent: '#0000FF',
    background: '#FFFFFF',
    border: '#0000FF',
    surface: '#ffffff',
    style: 'Brutalism + Motion-Driven',
    variant: 'light'
  },
  uiux_007: {
    label: '活力课堂',
    text: '#1e1b4b',
    muted: '#4c4a74',
    primary: '#4f46e5',
    soft: '#FFFFFF',
    codeBg: '#312e81',
    codeText: '#fff7ed',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#ADD8E6',
    surface: '#ffffff',
    style: 'Claymorphism + Vibrant & Block-based',
    variant: 'education'
  },
  uiux_008: {
    label: '高端地产',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0077B6',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#FFD700',
    background: '#FFFFFF',
    border: '#FFD700',
    surface: '#ffffff',
    style: 'Glassmorphism + Minimalism',
    variant: 'light'
  },
  uiux_010: {
    label: '餐饮美食',
    text: '#1f2937',
    muted: '#6b3f22',
    primary: '#FF6B35',
    soft: '#FFFAF0',
    codeBg: '#431407',
    codeText: '#fff7ed',
    accent: '#8B4513',
    background: '#FFFAF0',
    border: '#8B4513',
    surface: '#ffffff',
    style: 'Vibrant & Block-based + Motion-Driven',
    variant: 'light'
  },
  uiux_012: {
    label: '旅行探索',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#FF7F00',
    background: '#FFFFFF',
    border: '#FF7F00',
    surface: '#ffffff',
    style: 'Aurora UI + Motion-Driven',
    variant: 'light'
  },
  uiux_014: {
    label: '美业疗愈',
    text: '#3f1d2f',
    muted: '#7f4f63',
    primary: '#DB7093',
    soft: '#FFF5F5',
    codeBg: '#4a1832',
    codeText: '#fff1f2',
    accent: '#D4A017',
    background: '#FFF5F5',
    border: '#90EE90',
    surface: '#ffffff',
    style: 'Soft UI Evolution + Neumorphism',
    variant: 'light'
  },
  uiux_017: {
    label: '法律权威',
    text: '#0f172a',
    muted: '#475569',
    primary: '#1E3A5F',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#D4A017',
    background: '#FFFFFF',
    border: '#FFD700',
    surface: '#ffffff',
    style: 'Trust & Authority + Minimalism',
    variant: 'light'
  },
  uiux_018: {
    label: '婚礼活动',
    text: '#4a2534',
    muted: '#7f4f63',
    primary: '#DB7093',
    soft: '#FFFAF5',
    codeBg: '#4a1832',
    codeText: '#fff1f2',
    accent: '#D4A017',
    background: '#FFFAF5',
    border: '#FFD700',
    surface: '#ffffff',
    style: 'Soft UI Evolution + Aurora UI',
    variant: 'light'
  },
  uiux_019: {
    label: '共创空间',
    text: '#3f1d2f',
    muted: '#7f4f63',
    primary: '#DB7093',
    soft: '#FFF5F5',
    codeBg: '#4a1832',
    codeText: '#fff1f2',
    accent: '#D4A017',
    background: '#FFF5F5',
    border: '#90EE90',
    surface: '#ffffff',
    style: 'Vibrant & Block-based + Glassmorphism',
    variant: 'light'
  },
  uiux_020: {
    label: '可持续平台',
    text: '#111827',
    muted: '#475569',
    primary: '#10B981',
    soft: '#F5F5F5',
    codeBg: '#064e3b',
    codeText: '#ecfdf5',
    accent: '#6366F1',
    background: '#F5F5F5',
    border: '#10B981',
    surface: '#ffffff',
    style: 'Organic Biophilic + Minimalism',
    variant: 'light'
  },
  uiux_021: {
    label: '宠物护理',
    text: '#1f2937',
    muted: '#7c4a1c',
    primary: '#FF9F43',
    soft: '#FFF8F0',
    codeBg: '#431407',
    codeText: '#fff7ed',
    accent: '#87CEEB',
    background: '#FFF8F0',
    border: '#87CEEB',
    surface: '#ffffff',
    style: 'Claymorphism + Vibrant & Block-based',
    variant: 'education'
  },
  uiux_022: {
    label: '宠物医疗',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Soft UI Evolution + Accessible & Ethical',
    variant: 'light'
  },
  uiux_023: {
    label: '宠物领养',
    text: '#1f2937',
    muted: '#7c4a1c',
    primary: '#FF9F43',
    soft: '#FFF8F0',
    codeBg: '#431407',
    codeText: '#fff7ed',
    accent: '#87CEEB',
    background: '#FFF8F0',
    border: '#87CEEB',
    surface: '#ffffff',
    style: 'Motion-Driven + Claymorphism',
    variant: 'education'
  },
  uiux_024: {
    label: '医疗门诊',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Accessible & Ethical + Minimalism',
    variant: 'light'
  },
  uiux_025: {
    label: '远程医疗',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0284c7',
    soft: '#F5F5F5',
    codeBg: '#0f172a',
    codeText: '#f0f9ff',
    accent: '#22C55E',
    background: '#F5F5F5',
    border: '#90EE90',
    surface: '#ffffff',
    style: 'Soft UI Evolution + AI-Native UI',
    variant: 'light'
  },
  uiux_026: {
    label: '心理健康',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0284c7',
    soft: '#F5F5F5',
    codeBg: '#0f172a',
    codeText: '#f0f9ff',
    accent: '#22C55E',
    background: '#F5F5F5',
    border: '#90EE90',
    surface: '#ffffff',
    style: 'Neumorphism + Accessible & Ethical',
    variant: 'light'
  },
  uiux_027: {
    label: '数字银行',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Glassmorphism + Trust & Authority',
    variant: 'light'
  },
  uiux_029: {
    label: '支付网关',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Minimalism + Trust & Authority',
    variant: 'light'
  },
  uiux_035: {
    label: 'NFT 艺廊',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Minimalism + Motion-Driven',
    variant: 'light'
  },
  uiux_037: {
    label: '销售 CRM',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Feature-Rich Showcase + Trust & Authority',
    variant: 'light'
  },
  uiux_038: {
    label: '客服 CRM',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Soft UI Evolution + Feature-Rich Showcase',
    variant: 'light'
  },
  uiux_039: {
    label: 'AI 写作助手',
    text: '#111827',
    muted: '#475569',
    primary: '#6366F1',
    soft: '#F5F5F5',
    codeBg: '#111827',
    codeText: '#f8fafc',
    accent: '#10B981',
    background: '#F5F5F5',
    border: '#10B981',
    surface: '#ffffff',
    style: 'AI-Native UI + Minimalism',
    variant: 'light'
  },
  uiux_041: {
    label: 'Micro SaaS',
    text: '#0f172a',
    muted: '#475569',
    primary: '#0080FF',
    soft: '#FFFFFF',
    codeBg: '#0f172a',
    codeText: '#f8fafc',
    accent: '#22C55E',
    background: '#FFFFFF',
    border: '#8B00FF',
    surface: '#ffffff',
    style: 'Minimalism + Speed-focused',
    variant: 'light'
  },
  agent_builder_daily: {
    label: 'Agent Builder 日报',
    text: '#111827',
    muted: '#64748b',
    primary: '#4f46e5',
    soft: '#f8fafc',
    codeBg: '#111827',
    codeText: '#f8fafc',
    accent: '#7c83ff',
    background: '#ffffff',
    border: '#e5ecf6',
    surface: '#f8fafc',
    style: 'Grid Paper + Editorial Agent Builder',
    variant: 'agentBuilder'
  }
}

export const wechatThemeOptions = Object.entries(themes)
  .filter(([key]) => key.startsWith('uiux_') || key === 'agent_builder_daily')
  .map(([value, theme]) => ({
    label: theme.label || value,
    value
  }))
